<?php

/*****************************************************
TABLE DEFAULT DEFINES
*****************************************************/
	$table_default_header_type = array(
					'WIDTH' => 6,
					'T_COLOR' => array(10,10,10),
					'T_SIZE' => 10,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'T_TYPE' => 'B',
					'LN_SIZE' => 4,
					'BG_COLOR' => array(0,199,229),
					'BRD_COLOR' => array(0,92,177),
					'BRD_SIZE' => 0.2,
					'BRD_TYPE' => '1',
					'BRD_TYPE_NEW_PAGE' => '',
					'TEXT' => '',
					);
	$table_default_data_type = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 8,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'N',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 4,
					'BG_COLOR' => array(255,255,255),
					'BRD_COLOR' => array(0,92,177),
					'BRD_SIZE' => 0.1,
					'BRD_TYPE' => '1',
					'BRD_TYPE_NEW_PAGE' => '',
					);
	$table_default_table_type = array(
					'TB_ALIGN' => 'L',
					'L_MARGIN' => 5,
					'BRD_COLOR' => array(0,92,177),
					'BRD_SIZE' => '0.3',
					);
/*****************************************************
TABLE DEFAULT DEFINES --- END
*****************************************************/
?>